### ISSUE TITLE
函数十一题计算最大的三位约数求助，为什么int main改成 int kkk就可以过了，但是改了后vscode上跑不了，改前在vscode上可以

### ISSUE THREAD

**Issue by asddGfqewf** [chenxie95/SJTU_C-_Cource#14]
#include <iostream>
using namespace std;

int Func(int n);

int kkk()
{
    int w;
    cin>>w;
    int a= Func(w);
    if (a==0)
    {cout<<"Input error!";}
    else if (a==-1)
    {cout<<"Not found!";}
    else
    cout<<a;
}

int Func(int n)
{
    int i;
    if (n<1000 || n>1000000)
    {
        return 0;
    }
    else 
    {
        for (i=999;i>99;--i)
        {
            if(n % i ==0)
            {
                return i;
            }

        }

        if(i==99)
        {
            return -1;
        }
    }
}

**Comment by Liangzheng-ZL** [comment]
请注意题目要求：“完成函数int Func(int n)”，不需要用户自己添加main()函数，只需提交函数int Func(int n)部分即可。
